name: Publish Docs

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 120
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Run fsdocs
      run: dotnet fsdocs build --eval --properties Configuration=Release --parameters fsdocs-list-of-namespaces " "
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .\tmp\watch
        publish_branch: gh-pages
        force_orphan: true